# WorkFlow
## Load the data
## Clean the data
## Feature Enginnering
## Preproccessing
## Modelling
## Find the accuracy of the model and save the model

## Load the data

## Load the data

In [1]:
import pandas as pd

In [2]:
from helper_funtions import feature_enginnering,other

In [3]:
data = pd.read_csv('./data/raw/covid_19_data.csv')

In [4]:
data.head()

SNo ObservationDate Province/State  Country/Region      Last Update  \
0    1      01/22/2020          Anhui  Mainland China  1/22/2020 17:00   
1    2      01/22/2020        Beijing  Mainland China  1/22/2020 17:00   
2    3      01/22/2020      Chongqing  Mainland China  1/22/2020 17:00   
3    4      01/22/2020         Fujian  Mainland China  1/22/2020 17:00   
4    5      01/22/2020          Gansu  Mainland China  1/22/2020 17:00   

   Confirmed  Deaths  Recovered  
0        1.0     0.0        0.0  
1       14.0     0.0        0.0  
2        6.0     0.0        0.0  
3        1.0     0.0        0.0  
4        0.0     0.0        0.0

In [5]:
data = data.drop(['SNo','Province/State','Last Update'],axis=1)

In [6]:
data.head()

ObservationDate  Country/Region  Confirmed  Deaths  Recovered
0      01/22/2020  Mainland China        1.0     0.0        0.0
1      01/22/2020  Mainland China       14.0     0.0        0.0
2      01/22/2020  Mainland China        6.0     0.0        0.0
3      01/22/2020  Mainland China        1.0     0.0        0.0
4      01/22/2020  Mainland China        0.0     0.0        0.0

In [7]:
len(data)

281487

In [8]:
data =data.rename({'Country/Region':'Country','ObservationDate':'Date'},axis=1)

In [9]:
data.head()

Date         Country  Confirmed  Deaths  Recovered
0  01/22/2020  Mainland China        1.0     0.0        0.0
1  01/22/2020  Mainland China       14.0     0.0        0.0
2  01/22/2020  Mainland China        6.0     0.0        0.0
3  01/22/2020  Mainland China        1.0     0.0        0.0
4  01/22/2020  Mainland China        0.0     0.0        0.0

## Clean the data

In [10]:
data.head()

Date         Country  Confirmed  Deaths  Recovered
0  01/22/2020  Mainland China        1.0     0.0        0.0
1  01/22/2020  Mainland China       14.0     0.0        0.0
2  01/22/2020  Mainland China        6.0     0.0        0.0
3  01/22/2020  Mainland China        1.0     0.0        0.0
4  01/22/2020  Mainland China        0.0     0.0        0.0

In [11]:
from helper_funtions.other import *

In [12]:
o = Other()

In [13]:
index = -1
info_list = []
info_dict = {}
for info in data['Country']:
    if info not in info_dict:
            index += 1
            info_dict[info] = index
for info in data['Country']:
    info_list.append(info_dict[info])

In [14]:
data['Country'] = info_list

In [15]:
data.dtypes

Date          object
Country        int64
Confirmed    float64
Deaths       float64
Recovered    float64
dtype: object

In [16]:
data['Deaths'] = data['Deaths'].astype(int)

In [17]:
data['Recovered'] = data['Recovered'].astype(int)
data['Confirmed'] = data['Confirmed'].astype(int)

In [18]:
data.dtypes

Date         object
Country       int64
Confirmed     int64
Deaths        int64
Recovered     int64
dtype: object

In [19]:
data = o.replace_strs(data,'Date','/','')[0]

Checking if the columns dtype if object or not...
object
The columns dtype if object.
returning the data and the list of converted info


In [20]:
data.head()

Date  Country  Confirmed  Deaths  Recovered
0  01222020        0          1       0          0
1  01222020        0         14       0          0
2  01222020        0          6       0          0
3  01222020        0          1       0          0
4  01222020        0          0       0          0

In [21]:
data.tail()

Date  Country  Confirmed  Deaths  Recovered
281482  04272021       83      94375    1854      75409
281483  04272021       55      25243     233          0
281484  04272021        0       1332       1       1320
281485  04272021       83      83314    1565      65414
281486  04272021       55     350731    4119          0

In [22]:
data.dtypes

Date         object
Country       int64
Confirmed     int64
Deaths        int64
Recovered     int64
dtype: object

In [23]:
data['Date'] = data['Date'].astype(int)

## feature enginnering

In [24]:
from helper_funtions.feature_enginnering import FeatureEnginnering

In [25]:
fe = FeatureEnginnering(data,'Country')
data = fe.feature_enginner(quantile=True)

281487
266753


In [26]:
len(data)

266753

## Preproccessing

In [27]:
pres = o.preproccessing_methods()

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
X = data[['Date','Country']]
y = data.drop(['Date','Country'],axis=1)

In [30]:
from sklearn.ensemble import GradientBoostingRegressor

In [31]:
y = y['Recovered']

In [32]:
X_old = X
y_old = y

In [33]:
model = GradientBoostingRegressor().fit(X,y)
print(model.score(X,y))

0.27168527630920813


In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)

## Modelling

In [36]:
X_train = torch.from_numpy(np.array(X_train).astype(np.float32))

In [37]:
y_train

225093    3733
280664       0
258522       0
155638      23
105409     823
          ... 
61812       26
203753    4895
135638    1186
90431     3010
237498    9204
Name: Recovered, Length: 200064, dtype: int64

In [38]:
X_test = torch.from_numpy(np.array(X_test).astype(np.float32))
y_train = torch.from_numpy(np.array(y_train).astype(np.float32))
y_test = torch.from_numpy(np.array(y_test).astype(np.float32))

In [39]:
y_train

tensor([3733.,    0.,    0.,  ..., 1186., 3010., 9204.])

In [40]:
X_train.shape

torch.Size([200064, 2])

In [41]:
X_test.shape

torch.Size([66689, 2])

In [42]:
y_test.shape

torch.Size([66689])

In [43]:
y_train.shape

torch.Size([200064])

In [44]:
y_train.shape

torch.Size([200064])

In [45]:
y_train

tensor([3733.,    0.,    0.,  ..., 1186., 3010., 9204.])

In [46]:
y_train = y_train.view(y_train.shape[0],1)

In [47]:
y_train

tensor([[3733.],
        [   0.],
        [   0.],
        ...,
        [1186.],
        [3010.],
        [9204.]])

In [48]:
y_test = y_test.view(y_test.shape[0],1)

In [49]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [50]:
class Model(nn.Module):
    def __init__(self,nerons):
        super().__init__()
        self.fc1 = nn.Linear(2,nerons)
        self.fc2 = nn.Linear(nerons,nerons)
        self.fc3 = nn.Linear(nerons,1)
    
    def forward(self,x):
        y_preds = self.fc1(x)
        y_preds = self.fc2(y_preds)
        y_preds = self.fc3(y_preds)
        return y_preds

In [51]:
## best epochs
## best lr
## best loss
## best optimizer
## best num of layers
## best num of neurons

In [52]:
import wandb

In [53]:
# ## best epochs
# epochs_to_try = [100,125,250,500,750,1000,1250,2500]
# for epoch_to_try in epochs_to_try:
#     wandb.init(project='Covid19-Recoverd-Predictions',name=f'epochs-{epoch_to_try}')
#     model = Model(50)
#     crietion = nn.MSELoss()
#     optimizer = torch.optim.Adam(model.parameters(),lr=0.001)
#     for epoch in range(epoch_to_try):
#         y_preds = model(X_train)
#         loss = crietion(y_preds,y_train)
#         loss.backward()
#         optimizer.step()
#         optimizer.zero_grad()
#         wandb.log({'loss':loss,'epoch':epoch})
#     wandb.finish()

In [54]:
# ## best lr
# lrs = [1.0,0.1,0.01,0.001,0.0001]
# for lr in lrs:
#     wandb.init(project='Covid19-Recoverd-Predictions',name=f'lr-{lr}')
#     model = Model(50)
#     crietion = nn.MSELoss()
#     optimizer = torch.optim.Adam(model.parameters(),lr=lr)
#     for epoch in range(100):
#         y_preds = model(X_train)
#         loss = crietion(y_preds,y_train)
#         loss.backward()
#         optimizer.step()
#         optimizer.zero_grad()
#         wandb.log({'loss':loss,'epoch':epoch})
#     wandb.finish()

In [55]:
# ## best optimizer
# optimizers = [torch.optim.SGD,torch.optim.Adam,torch.optim.AdamW,torch.optim.Adamax]
# for optimizer in optimizers:
#     wandb.init(project='Covid19-Recoverd-Predictions',name=f'optimizer-{optimizer}')
#     model = Model(50)
#     crietion = nn.MSELoss()
#     optimizer = optimizer(model.parameters(),lr=0.001)
#     for epoch in range(100):
#         y_preds = model(X_train)
#         loss = crietion(y_preds,y_train)
#         loss.backward()
#         optimizer.step()
#         optimizer.zero_grad()
#         wandb.log({'loss':loss,'epoch':epoch})
#     wandb.finish()

In [56]:
# ## best num of neurons
# num_of_neurons = [1,2,3,4,5,6,7,8,9,10,12,15,17,20,22]

# for num_of_neuron in num_of_neurons:
#     wandb.init(project='Covid19-Recoverd-Predictions',name=f'num_of_neuron-{num_of_neuron}')
#     model = Model(num_of_neuron)
#     crietion = nn.MSELoss()
#     optimizer = torch.optim.Adam(model.parameters(),lr=0.001)
#     for epoch in range(100):
#         y_preds = model(X_train)
#         loss = crietion(y_preds,y_train)
#         loss.backward()
#         optimizer.step()
#         optimizer.zero_grad()
#         wandb.log({'loss':loss,'epoch':epoch})
#     wandb.finish()

In [57]:
# epochs = 362
# lr = 0.001
# optimizer = AdamX
# best num of neurons = 17
# loss = MSELoss

In [58]:
class Model(nn.Module):
    def __init__(self,nerons):
        super().__init__()
        self.fc1 = nn.Linear(2,nerons)
        self.fc2 = nn.Linear(nerons,nerons)
        self.fc3 = nn.Linear(nerons,1)
    
    def forward(self,x,num_layers=1):
        y_preds = self.fc1(x)
        for _ in range(num_layers):
            y_preds = self.fc2(y_preds)
        y_preds = self.fc3(y_preds)
        return y_preds

In [59]:
model = Model(17)

In [60]:
epochs = 362

In [61]:
lr = 0.001

In [62]:
optimizer = torch.optim.Adamax(model.parameters(),lr=lr)

In [63]:
crietion = torch.nn.MSELoss()

In [64]:
# num_of_layers = [62,75,100,112,125,150,175,200]
# for nol in num_of_layers:
#     wandb.init(project='Covid19-Recoverd-Predictions',name=f'num_of_layers-{nol}')
#     for epoch in range(epochs):
#         y_preds = model(X_train)
#         loss = crietion(y_preds,y_train)
#         loss.backward()
#         optimizer.step()
#         optimizer.zero_grad()
#         wandb.log({'loss':loss,'epoch':epoch})

In [65]:
# epochs = 362
# lr = 0.001
# optimizer = AdamX
# best num of neurons = 17
# loss = MSELoss
# num of layers = 175

In [66]:
num_of_neurons = 17
model = Model(num_of_neurons)
epochs = 362
lr = 0.001
optimizer = torch.optim.Adamax(model.parameters(),lr=lr)
crietion = torch.nn.MSELoss()
num_of_layers = 175

In [67]:
loss_logs = []
val_loss_logs = []
epoch_logs = []

In [68]:
wandb.init(project='Covid19-Recoverd-Predictions',name=f'Big-Dog-Model-0')
for epoch in range(epochs):
    y_train_preds = model(X_train,num_of_neurons)
    loss = crietion(y_train_preds,y_train)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    with torch.no_grad():
        y_test_preds = model(X_test,num_of_neurons)
        loss_ = crietion(y_test_preds,y_test)
    wandb.log({'loss':loss,'val_loss':loss_})   
wandb.finish()

wandb: Currently logged in as: ranuga-d (use `wandb login --relogin` to force relogin)


In [69]:
logs = pd.DataFrame({'val_loss':val_loss_logs,'loss':loss_logs,'epoch':epoch_logs})
logs.to_csv('./output/logs/big-dog-model-0-logs.csv')

In [70]:
## Wandb Logs : https://wandb.ai/ranuga-d/Covid19-Recoverd-Predictions

In [71]:
y_train_preds

tensor([[10081.9111],
        [20150.1777],
        [15516.8711],
        ...,
        [48137.5703],
        [38681.8320],
        [14240.4482]], grad_fn=<AddmmBackward>)

In [79]:
y_train

tensor([[3733.],
        [   0.],
        [   0.],
        ...,
        [1186.],
        [3010.],
        [9204.]])

In [80]:
y_test_preds

tensor([[39248.8164],
        [33292.7461],
        [20149.7031],
        ...,
        [38824.5078],
        [48373.2695],
        [19393.1523]])

In [81]:
y_test

tensor([[    0.],
        [    0.],
        [ 5815.],
        ...,
        [    0.],
        [27304.],
        [  769.]])

In [82]:
data.head()

Date  Country  Confirmed  Deaths  Recovered
12  1222020        1          0       0          0
20  1222020        2          1       0          0
28  1222020        3          1       0          0
31  1222020        4          1       0          0
35  1222020        5          2       0          0

In [83]:
X_train

tensor([[2.1320e+06, 1.6900e+02],
        [4.2620e+06, 5.5000e+01],
        [3.2820e+06, 3.0000e+01],
        ...,
        [1.0182e+07, 8.3000e+01],
        [8.1820e+06, 2.9000e+01],
        [3.0120e+06, 3.1000e+01]])

In [86]:
model(torch.from_numpy(np.array([1222020,1]).astype(np.float32)))

tensor([231546.6875], grad_fn=<AddBackward0>)

In [87]:
torch.save(model,'./output/models/big-dog-model.pth')

# Done